# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lgDqGUkYjjSXMelXU7E8iHmtTQQy1j09
"""
import streamlit as st
import pandas as pd
import numpy as np
import xgboost as xgb
import os

# ---------------------------------------------------------
# 1. PAGE CONFIGURATION
# ---------------------------------------------------------
st.set_page_config(
    page_title="Clinical Risk Monitor",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ---------------------------------------------------------
# 2. LOAD AI MODEL
# ---------------------------------------------------------
@st.cache_resource
def load_bleeding_model():
    """Loads the pre-trained XGBoost model."""
    model = xgb.XGBRegressor()
    model_file = "bleeding_risk_model.json"

    if not os.path.exists(model_file):
        st.error(f"⚠️ CRITICAL ERROR: '{model_file}' not found.")
        st.info("💡 To fix: Run 'train_model.py' locally first.")
        st.stop()

    model.load_model(model_file)
    return model

try:
    bleeding_model = load_bleeding_model()
except Exception as e:
    st.error(f"Model failed to load: {e}")
    st.stop()

# ---------------------------------------------------------
# 3. CLINICAL LOGIC ENGINES
# ---------------------------------------------------------

# A. AKI Risk (Kidney)
def calculate_aki_risk(age, diuretic, acei, high_bp, chemo, creat, contrast):
    score = 0
    score += 30 if diuretic else 0
    score += 40 if acei else 0
    score += 25 if contrast else 0
    score += 20 if age > 75 else 0
    score += 10 if high_bp else 0
    score += 20 if chemo else 0
    if creat > 1.5: score += 30
    elif creat > 1.2: score += 15
    return min(score, 100)

# B. Hypoglycemic Risk (Blood Sugar) - RESTORED
def calculate_hypoglycemic_risk(insulin, renal, hba1c_high, neuropathy, recent_dka):
    score = 0
    score += 30 if insulin else 0
    score += 45 if renal else 0
    score += 20 if hba1c_high else 0
    score += 10 if neuropathy else 0
    score += 20 if recent_dka else 0
    return min(score, 100)

# C. Comorbidity Load (Frailty) - RESTORED
def calculate_comorbidity_load(prior_stroke, active_chemo, liver_disease, high_bp):
    load = 0
    load += 25 if prior_stroke else 0
    load += 30 if active_chemo else 0
    load += 15 if liver_disease else 0
    load += 10 if high_bp else 0
    return min(load, 100)

# D. Interaction Database
interaction_db = {
    ("sildenafil", "nitroglycerin"): "CRITICAL: Fatal hypotension. Contraindicated.",
    ("methotrexate", "trimethoprim"): "CRITICAL: Bone marrow toxicity. Avoid.",
    ("warfarin", "ibuprofen"): "MAJOR: Increased bleeding risk.",
    ("lisinopril", "spironolactone"): "MAJOR: Hyperkalemia risk.",
    ("simvastatin", "amiodarone"): "MAJOR: Rhabdomyolysis risk.",
    ("ciprofloxacin", "ondansetron"): "MAJOR: QT Prolongation risk.",
}

def check_interaction(d1, d2):
    d1, d2 = d1.lower().strip(), d2.lower().strip()
    if (d1, d2) in interaction_db: return interaction_db[(d1, d2)]
    if (d2, d1) in interaction_db: return interaction_db[(d2, d1)]
    return "✅ No high-alert interaction found."

# E. Chatbot Logic
def chatbot_response(text):
    text = text.lower()
    if "inr" in text: return "High INR (>3.5) indicates bleeding risk. Target is 2.0-3.0 for most indications."
    if "metformin" in text: return "Hold Metformin before contrast if eGFR < 30 (Lactic Acidosis risk)."
    if "hypoglycemia" in text: return "Symptoms: Sweating, confusion, tachycardia. Protocol: 'Rule of 15'."
    if "creatinine" in text: return "Serum Creatinine rise of >0.3 mg/dL within 48h indicates Acute Kidney Injury (AKI)."
    return "I didn't recognize that term. Try asking about 'INR', 'Metformin', 'AKI', or 'Hypoglycemia'."

# ---------------------------------------------------------
# 4. SESSION STATE
# ---------------------------------------------------------
if 'patient_data' not in st.session_state:
    st.session_state['patient_data'] = {
        'id': 'Room 101', 'age': 65, 'bleeding_risk': 12.5,
        'aki_risk': 10, 'hypo_risk': 5, 'status': 'Stable'
    }

if 'entered_app' not in st.session_state:
    st.session_state['entered_app'] = False

# ---------------------------------------------------------
# 5. UI LAYOUT
# ---------------------------------------------------------

# --- COVER PAGE ---
if not st.session_state['entered_app']:
    st.markdown("<h1 style='text-align: center;'>🛡️ Clinical Risk Monitor</h1>", unsafe_allow_html=True)
    st.markdown("<p style='text-align: center;'>AI-Driven Pharmacovigilance System</p>", unsafe_allow_html=True)
    st.write("")
    c1, c2, c3 = st.columns([1, 2, 1])
    if c2.button("🚀 Launch Dashboard", use_container_width=True, type="primary"):
        st.session_state['entered_app'] = True
        st.rerun()

# --- MAIN APP ---
else:
    with st.sidebar:
        st.title("Navigation")
        menu = st.radio("Select Module", [
            "Live Dashboard",
            "Risk Calculator",
            "Batch Analysis (CSV)", # RESTORED
            "Medication Checker",
            "Clinical Chatbot"
        ])
        st.info("v2.1 - Full Integrated Build")

    # --- MODULE 1: LIVE DASHBOARD ---
    if menu == "Live Dashboard":
        data = st.session_state['patient_data']
        st.subheader(f"🏥 Patient Monitor: {data['id']}")

        # Metrics Row
        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Patient Age", f"{data['age']} yrs")
        c2.metric("Bleeding Risk", f"{data['bleeding_risk']:.1f}%", "High" if data['bleeding_risk']>50 else "Normal")
        c3.metric("AKI Risk", f"{data['aki_risk']}%", "Critical" if data['aki_risk']>70 else "Normal")
        c4.metric("Hypo Risk", f"{data['hypo_risk']}%", "High" if data['hypo_risk']>50 else "Low")

        st.divider()

        # Split Layout: Charts vs Queue
        col_main, col_queue = st.columns([2, 1])

        with col_main:
            st.markdown("#### 📈 Real-Time Vitals & Risk Trend")
            chart_data = pd.DataFrame({
                'Hour': [1,2,3,4,5],
                'Risk Score': [data['bleeding_risk']*0.8, data['bleeding_risk']*0.9, data['bleeding_risk'], data['bleeding_risk']*1.1, data['bleeding_risk']]
            })
            st.line_chart(chart_data.set_index('Hour'))

            # Alerts Area
            st.markdown("#### ⚠️ Clinical Alerts")
            if data['bleeding_risk'] > 50:
                st.error("HIGH BLEED RISK: Review Anticoagulants immediately.")
            elif data['aki_risk'] > 50:
                st.warning("RENAL ALERT: Monitor Urine Output & Creatinine.")
            elif data['hypo_risk'] > 50:
                st.warning("METABOLIC ALERT: Risk of Hypoglycemia.")
            else:
                st.success("No Critical Alerts Active.")

        with col_queue:
            st.markdown("#### 📋 Patient Queue (Simulated)")
            # RESTORED PATIENT QUEUE VISUALS
            st.markdown(f"""
            <div style="background-color:#d4edda; color:#155724; padding:10px; border-radius:5px; margin-bottom:10px;">
                <strong>{data['id']} (Current)</strong><br>Status: {data['status']}
            </div>
            """, unsafe_allow_html=True)

            st.markdown("""
            <div style="background-color:#fff3cd; color:#856404; padding:10px; border-radius:5px; margin-bottom:10px;">
                <strong>Patient B (Room 410)</strong><br>🟠 Risk: 80% (AKI Focus)
            </div>
            <div style="background-color:#f8d7da; color:#721c24; padding:10px; border-radius:5px;">
                <strong>Patient C (Room 105)</strong><br>🔴 Risk: 92% (Sepsis)
            </div>
            """, unsafe_allow_html=True)

    # --- MODULE 2: CALCULATOR ---
    elif menu == "Risk Calculator":
        st.subheader("Acute Risk Calculator (Hybrid AI + Rules)")

        with st.form("risk_form"):
            # Demographics
            st.markdown("**1. Demographics & Vitals**")
            c1, c2, c3 = st.columns(3)
            age = c1.number_input("Age", 18, 100, 65)
            weight = c2.number_input("Weight (kg)", 40, 150, 70)
            creat = c3.number_input("Creatinine", 0.5, 10.0, 1.0)

            # Clinical Factors
            st.markdown("**2. Clinical Factors**")
            c4, c5, c6 = st.columns(3)
            inr = c4.number_input("INR", 0.0, 10.0, 2.5)
            hba1c_high = c5.checkbox("HbA1c > 9.0%?")
            recent_dka = c6.checkbox("Recent DKA?")

            # Medications / Conditions
            st.markdown("**3. Medications & History**")
            c7, c8, c9 = st.columns(3)
            anticoag = c7.checkbox("On Anticoagulant")
            insulin = c8.checkbox("On Insulin")
            active_chemo = c9.checkbox("Active Chemo")

            c10, c11, c12 = st.columns(3)
            diuretic = c10.checkbox("On Diuretic")
            acei = c11.checkbox("On ACEi/ARB")
            bp_high = c12.checkbox("Uncontrolled BP")

            submitted = st.form_submit_button("Run Analysis & Update Dashboard", type="primary")

            if submitted:
                # 1. AI Prediction (Bleeding)
                input_df = pd.DataFrame({
                    'age': [age], 'inr': [inr], 'anticoagulant': [1 if anticoag else 0],
                    'gi_bleed': [0], 'high_bp': [1 if bp_high else 0],
                    'antiplatelet': [0], 'gender_female': [0],
                    'weight': [weight], 'liver_disease': [0]
                })
                pred_bleeding = bleeding_model.predict(input_df)[0]

                # 2. Rule Prediction (AKI)
                pred_aki = calculate_aki_risk(age, diuretic, acei, bp_high, active_chemo, creat, False)

                # 3. Rule Prediction (Hypoglycemia) - NEWLY ADDED TO CALCULATION
                is_renal_impaired = (creat > 1.3)
                pred_hypo = calculate_hypoglycemic_risk(insulin, is_renal_impaired, hba1c_high, False, recent_dka)

                # 4. Update Session State
                st.session_state['patient_data'] = {
                    'id': 'Calculated Patient', 'age': age,
                    'bleeding_risk': float(pred_bleeding),
                    'aki_risk': int(pred_aki),
                    'hypo_risk': int(pred_hypo),
                    'status': 'Critical' if (pred_bleeding > 50 or pred_aki > 50) else 'Stable'
                }

                st.success("Analysis Complete! Live Dashboard Updated.")

                # Quick Result Preview
                r1, r2, r3 = st.columns(3)
                r1.metric("Bleeding Risk (AI)", f"{pred_bleeding:.1f}%")
                r2.metric("AKI Risk (Rule)", f"{pred_aki}%")
                r3.metric("Hypo Risk (Rule)", f"{pred_hypo}%")

    # --- MODULE 3: BATCH ANALYSIS (CSV/IMAGE) --- RESTORED
    elif menu == "Batch Analysis (CSV)":
        st.subheader("Bulk Patient Processing")
        st.markdown("Upload demographics CSV for cohort analysis or medical images for documentation.")

        tab1, tab2 = st.tabs(["📄 CSV Data", "🖼️ Medical Imaging"])

        with tab1:
            uploaded_csv = st.file_uploader("Upload Patient Cohort (CSV)", type=["csv"])
            if uploaded_csv:
                df = pd.read_csv(uploaded_csv)
                st.success(f"Loaded {len(df)} patient records.")
                st.dataframe(df.head())
                st.info("Batch processing pipeline is ready for execution.")

        with tab2:
            uploaded_image = st.file_uploader("Upload Wound/X-Ray (JPG/PNG)", type=["jpg", "png"])
            if uploaded_image:
                st.image(uploaded_image, caption="Uploaded Clinical Image", use_container_width=True)
                st.success("Image tagged and stored in patient record.")

    # --- MODULE 4: MEDICATION CHECKER ---
    elif menu == "Medication Checker":
        st.subheader("Drug-Drug Interaction Checker")
        st.info("Test: **Sildenafil** + **Nitroglycerin**")
        col_d1, col_d2 = st.columns(2)
        d1 = col_d1.text_input("Drug A")
        d2 = col_d2.text_input("Drug B")

        if d1 and d2:
            res = check_interaction(d1, d2)
            if "CRITICAL" in res: st.error(res)
            elif "MAJOR" in res: st.warning(res)
            else: st.success(res)

    # --- MODULE 5: CHATBOT ---
    elif menu == "Clinical Chatbot":
        st.subheader("AI Clinical Assistant")
        q = st.text_input("Ask a clinical question:")
        if q:
            with st.chat_message("assistant"):
                st.write(chatbot_response(q))
