import streamlit as st
import pandas as pd
import numpy as np
import altair as alt
import backend as bk
import random
import datetime
import json
import google.generativeai as genai

# --- CONFIGURATION: CONNECT TO AI ---
try:
    # This checks if the key exists in the cloud vault
    if "GEMINI_API_KEY" in st.secrets:
        genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
    else:
        # Fallback for local testing (optional, usually safer to use secrets.toml locally too)
        st.warning("⚠️ AI Key missing. Please add GEMINI_API_KEY to Streamlit Secrets.")
except Exception as e:
    st.error(f"⚠️ AI Configuration Error: {e}")

# --- 1. AI Extraction Function (Updated for Labs) ---
def extract_data_from_soap(note_text):
    """
    Uses Gemini to extract structured clinical data.
    """
    # Prioritize Lite model to avoid Quota limits
    candidate_models = [
        'gemini-2.0-flash-lite', 
        'gemini-2.0-flash',
        'gemini-flash-latest',
        'gemini-pro'
    ]

    prompt = f"""
    You are a clinical data extraction assistant. Extract the following values from the note.
    Return ONLY a valid JSON object. Do not add markdown formatting.
    If a value is not mentioned, return null.
    
    Keys to extract:
    # --- VITALS ---
    - age (integer)
    - gender (string: "Male" or "Female")
    - weight_kg (float)
    - height_cm (integer)
    - sbp (systolic bp, integer)
    - dbp (diastolic bp, integer)
    - hr (heart rate, integer)
    - rr (respiratory rate, integer)
    - temp_c (temperature in celsius, float)
    - o2_sat (integer)
    
    # --- LABS ---
    - creatinine (float)
    - bun (integer)
    - potassium (float)
    - glucose (integer)
    - wbc (float)
    - hgb (float)
    - platelets (integer)
    - inr (float)
    - lactate (float)
    
    # --- HISTORY / MEDS (Booleans) ---
    - anticoagulant_use (boolean: true if taking warfarin, eliquis, xarelto, heparin, etc.)
    - liver_disease (boolean: cirrhosis, hepatitis, etc.)
    - heart_failure (boolean: CHF, low EF)
    - gi_bleed (boolean: history of gastrointestinal bleeding)
    - nsaid_use (boolean: ibuprofen, motrin, naproxen, etc.)
    - active_chemo (boolean)
    - diuretic_use (boolean: lasix, furosemide, hctz)
    - acei_arb_use (boolean: lisinopril, losartan, etc.)
    - insulin_use (boolean)
    - uncontrolled_diabetes (boolean: high A1c mentioned)
    - altered_mental (boolean: confusion, lethargy, AMS)

    Clinical Note:
    "{note_text}"
    """

    last_error = None
    for model_name in candidate_models:
        try:
            model = genai.GenerativeModel(model_name)
            response = model.generate_content(prompt)
            cleaned_text = response.text.replace("```json", "").replace("```", "").strip()
            return json.loads(cleaned_text)
        except Exception as e:
            last_error = e
            continue

    st.error(f"❌ Extraction failed. Last error: {last_error}")
    return None

from fpdf import FPDF
import base64

def create_pdf_report(res, ai_assessment=""):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    
    # Header
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt="Clinical Risk Monitor - Acute Patient Report", ln=1, align='C')
    pdf.set_font("Arial", size=10)
    pdf.cell(200, 10, txt="Generated by AI Clinical CDSS", ln=1, align='C')
    pdf.line(10, 30, 200, 30)
    pdf.ln(10)

    # Patient Demographics
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, txt="1. Patient Profile", ln=1)
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"Age: {res.get('age')} | Gender: {res.get('gender')} | Weight: {res.get('weight_kg', res.get('weight', 0))} kg", ln=1)
    pdf.cell(200, 10, txt=f"Vitals: BP {res.get('sys_bp')}/{res.get('dia_bp')} | HR {res.get('hr')} | RR {res.get('resp_rate')} | SpO2 {res.get('o2_sat')}%", ln=1)
    pdf.ln(5)

    # Risk Stratification
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, txt="2. Risk Stratification Scores", ln=1)
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"- Bleeding Risk: {res.get('bleeding_risk'):.1f}%", ln=1)
    pdf.cell(200, 10, txt=f"- AKI Risk: {res.get('aki_risk')}%", ln=1)
    pdf.cell(200, 10, txt=f"- Sepsis (qSOFA): {res.get('sepsis_risk')}", ln=1)
    pdf.cell(200, 10, txt=f"- Shock Index: {res.get('shock_index'):.2f}", ln=1)
    pdf.ln(5)

    # AI Assessment
    if ai_assessment:
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(200, 10, txt="3. AI Clinical Assessment", ln=1)
        pdf.set_font("Arial", size=11)
        pdf.multi_cell(0, 10, txt=ai_assessment)
    
    # Save
    return pdf.output(dest='S').encode('latin-1')    
# ---------------------------------------------------------
# 1. PAGE CONFIGURATION
# ---------------------------------------------------------
st.set_page_config(
    page_title="Clinical Risk Monitor", 
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Load CSS (Called immediately after page config)
st.markdown("""
    <style>
    [data-testid="stSidebar"] {
        background-color: #f8f9fa;
        border-right: 1px solid #e9ecef;
    }
    [data-testid="stMetricValue"] {
        font-size: 1.8rem !important;
        color: #212529;
    }
    </style>
""", unsafe_allow_html=True)

st.title("🏥 Clinical Risk Monitor: High-Acuity IOP Dashboard")
st.markdown("""
**Objective:** A Measurement-Based Care (MBC) tool to predict **patient deterioration** and **readmission risk** in outpatient settings.
* **Key Features:** Medication Non-Adherence Tracking, Symptom Severity Scoring (PHQ-9/GAD-7), and Risk Stratification.
* **Tech Stack:** Python, Machine Learning (Scikit-Learn), Streamlit.
""")
st.divider()

# Helper for file timestamps
def get_timestamp():
    return datetime.datetime.now().strftime("%Y%m%d_%H%M")

# Initialize Database
bk.init_db()

# Load AI Model
try:
    bleeding_model = bk.load_bleeding_model()
except Exception as e:
    st.error(f"Model failed to load: {e}")
    st.stop()

# Session State Initialization
if 'patient_data' not in st.session_state:
    st.session_state['patient_data'] = {}
if 'entered_app' not in st.session_state:
    st.session_state['entered_app'] = False

# ---------------------------------------------------------
# 2. UI MODULES
# ---------------------------------------------------------

# --- COVER PAGE ---
def render_cover_page():
    st.markdown("<h1 style='text-align: center;'>🛡️ Clinical Risk Monitor</h1>", unsafe_allow_html=True)
    st.markdown("<p style='text-align: center;'>AI-Driven Pharmacovigilance System</p>", unsafe_allow_html=True)
    st.write("")
    c1, c2, c3 = st.columns([1, 2, 1])
    if c2.button("🚀 Launch Dashboard", use_container_width=True, type="primary"):
        st.session_state['entered_app'] = True
        st.rerun()

# --- MODULE 1: RISK CALCULATOR (COMPLETE & FIXED) ---
def render_risk_calculator():
    st.subheader("Acute Risk Calculator")
    
    # --- 1. INITIALIZE DEFAULTS (Prevents "KeyError" crashes) ---
    defaults = {
        # Demographics & Vitals
        'age_input': 0, 'gender_input': "Male", 
        'weight_input': 0.0, 'w_unit': 'kg', 'height_input': 0,
        'sbp_input': 0, 'dbp_input': 0, 'hr_input': 0, 'rr_input': 0, 
        'temp_input': 0.0, 'o2_input': 0,
        
        # Labs
        'creat_input': 0.0, 'bun_input': 0, 
        'k_input': 0.0, 'glc_input': 0, 
        'wbc_input': 0.0, 'hgb_input': 0.0, 
        'plt_input': 0, 'inr_input': 0.0, 'lac_input': 0.0,
        
        # History (Checkboxes)
        'anticoag_input': False, 'liver_input': False,
        'chf_input': False, 'gib_input': False,
        'nsaid_input': False, 'chemo_input': False,
        'diuretic_input': False, 'acei_input': False,
        'insulin_input': False, 'dm_input': False, 'ams_input': False
    }
    
    for key, default_val in defaults.items():
        if key not in st.session_state:
            st.session_state[key] = default_val

    # --- 2. AI AUTO-FILL SECTION ---
    with st.expander("⚡ AI Auto-Fill (Paste SOAP Note)"):
        st.caption("Paste a clinical note below to auto-populate vitals, labs, and history.")
        soap_note = st.text_area("Clinical Note", placeholder="Example: 68yo male, BP 150/90, HR 110, Cr 1.5, Lactate 4.0, hx of CHF...")
        
        if st.button("✨ Extract Data from Note"):
            if soap_note:
                with st.spinner("Gemini is extracting clinical data..."):
                    data = extract_data_from_soap(soap_note)
                    
                    if data:
                        # --- MAP AI DATA TO WIDGET KEYS ---
                        
                        # Vitals
                        if data.get('age'): st.session_state['age_input'] = int(data['age'])
                        if data.get('gender'): st.session_state['gender_input'] = data['gender']
                        if data.get('weight_kg'): 
                            st.session_state['weight_input'] = float(data['weight_kg'])
                            st.session_state['w_unit'] = 'kg'
                        if data.get('height_cm'): st.session_state['height_input'] = int(data['height_cm'])
                        if data.get('sbp'): st.session_state['sbp_input'] = int(data['sbp'])
                        if data.get('dbp'): st.session_state['dbp_input'] = int(data['dbp'])
                        if data.get('hr'): st.session_state['hr_input'] = int(data['hr'])
                        if data.get('rr'): st.session_state['rr_input'] = int(data['rr'])
                        if data.get('temp_c'): st.session_state['temp_input'] = float(data['temp_c'])
                        if data.get('o2_sat'): st.session_state['o2_input'] = int(data['o2_sat'])
                        
                        # Labs
                        if data.get('creatinine'): st.session_state['creat_input'] = float(data['creatinine'])
                        if data.get('bun'): st.session_state['bun_input'] = int(data['bun'])
                        if data.get('potassium'): st.session_state['k_input'] = float(data['potassium'])
                        if data.get('glucose'): st.session_state['glc_input'] = int(data['glucose'])
                        if data.get('wbc'): st.session_state['wbc_input'] = float(data['wbc'])
                        if data.get('hgb'): st.session_state['hgb_input'] = float(data['hgb'])
                        if data.get('platelets'): st.session_state['plt_input'] = int(data['platelets'])
                        if data.get('inr'): st.session_state['inr_input'] = float(data['inr'])
                        if data.get('lactate'): st.session_state['lac_input'] = float(data['lactate'])
                        
                        # History (Booleans)
                        if data.get('anticoagulant_use') is not None: st.session_state['anticoag_input'] = bool(data['anticoagulant_use'])
                        if data.get('liver_disease') is not None: st.session_state['liver_input'] = bool(data['liver_disease'])
                        if data.get('heart_failure') is not None: st.session_state['chf_input'] = bool(data['heart_failure'])
                        if data.get('gi_bleed') is not None: st.session_state['gib_input'] = bool(data['gi_bleed'])
                        if data.get('nsaid_use') is not None: st.session_state['nsaid_input'] = bool(data['nsaid_use'])
                        if data.get('active_chemo') is not None: st.session_state['chemo_input'] = bool(data['active_chemo'])
                        if data.get('diuretic_use') is not None: st.session_state['diuretic_input'] = bool(data['diuretic_use'])
                        if data.get('acei_arb_use') is not None: st.session_state['acei_input'] = bool(data['acei_arb_use'])
                        if data.get('insulin_use') is not None: st.session_state['insulin_input'] = bool(data['insulin_use'])
                        if data.get('uncontrolled_diabetes') is not None: st.session_state['dm_input'] = bool(data['uncontrolled_diabetes'])
                        if data.get('altered_mental') is not None: st.session_state['ams_input'] = bool(data['altered_mental'])
                        
                        st.success("✅ Data Extracted! Form updated below.")
                        st.rerun() 
            else:
                st.warning("Please paste a note first.")

    # --- 3. INPUTS CONTAINER ---
    with st.container(border=True):
        st.markdown("#### 📝 Patient Data Entry")
        
        with st.form("risk_form"):
            col_left, col_right = st.columns([1, 1], gap="medium")
            
            # --- LEFT COLUMN: Demographics & Vitals ---
            with col_left:
                st.markdown("##### 👤 Patient Profile")
                l1, l2 = st.columns(2)
                age = l1.number_input("Age (Years)", min_value=0, max_value=120, key='age_input')
                gender = l2.selectbox("Gender", ["Male", "Female"], key='gender_input')
                
                w_val, w_unit = st.columns([2, 1]) 
                weight_input = w_val.number_input("Weight", 0.0, 400.0, key='weight_input')
                weight_scale = w_unit.selectbox("Unit", ["kg", "lbs"], key="w_unit")
                height = st.number_input("Height (cm)", 0, 250, key='height_input')
                
                # Weight Logic
                weight_kg = weight_input * 0.453592 if weight_scale == "lbs" else weight_input
                if height > 0:
                    bmi = weight_kg / ((height/100)**2)
                else:
                    bmi = 0.0

                st.markdown("##### 🩺 Vitals")
                v1, v2 = st.columns(2)
                sys_bp = v1.number_input("Systolic BP (Normal: 110-120)", 0, 300, key='sbp_input')
                dia_bp = v2.number_input("Diastolic BP (Normal: 70-80)", 0, 200, key='dbp_input')
                
                v3, v4 = st.columns(2)
                hr = v3.number_input("Heart Rate (Normal: 60-100)", 0, 300, key='hr_input')
                resp_rate = v4.number_input("Resp Rate (Normal: 12-20)", 0, 60, key='rr_input')
                
                v5, v6 = st.columns(2)
                temp_c = v5.number_input("Temp °C (Normal: 36.5-37.5)", 0.0, 45.0, step=0.1, key='temp_input')
                o2_sat = v6.number_input("O2 Sat % (Normal: >95%)", 0, 100, key='o2_input')

            # --- RIGHT COLUMN: Labs & History ---
            with col_right:
                st.markdown("##### 🧪 Critical Labs")
                lab1, lab2 = st.columns(2)
                creat = lab1.number_input("Creatinine (0.6-1.2 mg/dL)", 0.0, 20.0, key='creat_input')
                bun = lab2.number_input("Blood Urea Nitrogen (7-20)", 0, 100, 0, key='bun_input')
                
                lab3, lab4 = st.columns(2)
                potassium = lab3.number_input("Potassium (3.5-5.0 mmol/L)", 0.0, 10.0, 0.0, key='k_input')
                glucose = lab4.number_input("Glucose (70-100 mg/dL)", 0, 1000, 0, key='glc_input')
                
                lab5, lab6 = st.columns(2)
                wbc = lab5.number_input("WBC (4.5-11.0 10^9/L)", 0.0, 50.0, 0.0, key='wbc_input')
                hgb = lab6.number_input("Hemoglobin (13.5-17.5 g/dL)", 0.0, 20.0, 0.0, key='hgb_input')
                
                lab7, lab8 = st.columns(2)
                platelets = lab7.number_input("Platelets (150-450 10^9/L)", 0, 1000, 0, key='plt_input')
                inr = lab8.number_input("INR (Clotting Time) [0.9-1.1]", 0.0, 10.0, key='inr_input')
                
                lactate = st.number_input("Lactate (Normal: < 2.0 mmol/L)", 0.0, 20.0, 0.0, key='lac_input')

                st.markdown("##### 📋 Medical History")
                h1, h2 = st.columns(2)
                anticoag = h1.checkbox("Anticoagulant Use", key='anticoag_input')
                liver_disease = h2.checkbox("Liver Disease", key='liver_input')
                
                h3, h4 = st.columns(2)
                heart_failure = h3.checkbox("Heart Failure", key='chf_input')
                gi_bleed = h4.checkbox("History of GI Bleed", key='gib_input')
                
                m1, m2 = st.columns(2)
                nsaid = m1.checkbox("NSAID Use", key='nsaid_input')
                active_chemo = m2.checkbox("Active Chemo", key='chemo_input')
                
                m3, m4 = st.columns(2)
                diuretic = m3.checkbox("Diuretic Use", key='diuretic_input')
                acei = m4.checkbox("ACEi/ARB", key='acei_input')
                
                m5, m6 = st.columns(2)
                insulin = m5.checkbox("Insulin", key='insulin_input')
                hba1c_high = m6.checkbox("Uncontrolled Diabetes", key='dm_input')
                
                altered_mental = st.checkbox("Altered Mental Status (Confusion)", key='ams_input')
                pain = 0

            st.write("") 
            submitted = st.form_submit_button("🚀 Run Clinical Analysis", type="primary", use_container_width=True)

    # --- LOGIC & RESULTS ---
    if submitted:
        # 1. Calc Hemodynamics
        final_temp_c = temp_c 
        if sys_bp > 0:
            map_val = (sys_bp + (2 * dia_bp)) / 3 
            pulse_pressure = sys_bp - dia_bp
            shock_index = hr / sys_bp if sys_bp > 0 else 0
        else:
            map_val, pulse_pressure, shock_index = 0, 0, 0
        
        bun_creat_ratio = bun / creat if creat > 0 else 0
        
        # 2. Run ML Model (Bleeding Risk)
        if age > 0 and sys_bp > 0:
            input_df = pd.DataFrame({
                'age': [age], 'inr': [inr], 'systolic_bp': [sys_bp], 
                'anticoagulant': [1 if anticoag else 0], 'gender': [gender],
                'liver_disease': [1 if liver_disease else 0]
            })
            try:
                # Try prediction (XGBoost)
                pred_bleeding = bleeding_model.predict_proba(input_df)[0][1] * 100
            except AttributeError:
                # Fallback (Regressor)
                pred_bleeding = float(bleeding_model.predict(input_df)[0])

            # 3. Run Clinical Rules
            pred_aki = bk.calculate_aki_risk(age, diuretic, acei, sys_bp, active_chemo, creat, nsaid, heart_failure)
            pred_sepsis = bk.calculate_sepsis_risk(sys_bp, resp_rate, altered_mental, final_temp_c)
            pred_hypo = bk.calculate_hypoglycemic_risk(insulin, (creat>1.3), hba1c_high, False)
            sirs_score = bk.calculate_sirs_score(final_temp_c, hr, resp_rate, wbc)
            
            # HAS-BLED (Manual Check)
            has_bled = 0 
            if sys_bp > 160: has_bled += 1
            if creat > 2.2 or liver_disease: has_bled += 1
            if gi_bleed: has_bled += 1
            if inr > 1.0: has_bled += 1
            if age > 65: has_bled += 1
            if nsaid or anticoag: has_bled += 1
            
        else:
            pred_bleeding, pred_aki, pred_sepsis, pred_hypo, sirs_score, has_bled = 0.0, 0, 0, 0, 0, 0
            
        status_calc = 'Critical' if (pred_bleeding > 50 or pred_aki > 50 or pred_sepsis >= 2) else 'Stable'
        
        # 4. Save to Database
        bk.save_patient_to_db(age, gender, sys_bp, int(pred_aki), float(pred_bleeding), status_calc)
        
        # 5. Save Results to Session
        st.session_state['analysis_results'] = {
            'bleeding_risk': float(pred_bleeding), 'aki_risk': int(pred_aki),
            'sepsis_risk': int(pred_sepsis), 'hypo_risk': int(pred_hypo),
            'sirs_score': sirs_score, 'status': status_calc, 'map_val': map_val, 
            'shock_index': shock_index, 'pulse_pressure': pulse_pressure,
            'age': age, 'sys_bp': sys_bp, 'inr': inr, 'anticoag': anticoag,
            'resp_rate': resp_rate, 'altered_mental': altered_mental, 
            'temp_c': temp_c, 'o2_sat': o2_sat, 'hr': hr, 'dia_bp': dia_bp,
            'glucose': glucose, 'potassium': potassium, 'hgb': hgb, 'wbc': wbc, 
            'platelets': platelets, 'lactate': lactate, 'creat': creat,
            'diuretic': diuretic, 'acei': acei, 'liver_disease': liver_disease, 'heart_failure': heart_failure
        }

    # --- RESULTS DISPLAY (COLOR CORRECTED) ---
    if 'analysis_results' in st.session_state:
        res = st.session_state['analysis_results']
        
        st.divider()
        st.subheader("📊 Risk Stratification Results")
        
        # Row 1: The Major Scores
        r1, r2, r3, r4 = st.columns(4)
        
        # 1. Bleeding Risk (Red if > 50%)
        b_risk = res['bleeding_risk']
        r1.metric(
            "🩸 Bleeding Risk", 
            f"{b_risk:.1f}%", 
            "High" if b_risk > 50 else "Normal", 
            delta_color="inverse" if b_risk > 50 else "normal",
            help="XGBoost Prediction"
        )
        
        # 2. AKI Risk (Red if > 50%)
        a_risk = res['aki_risk']
        r2.metric(
            "💧 AKI Risk", 
            f"{a_risk}%", 
            "High" if a_risk > 50 else "Normal", 
            delta_color="inverse" if a_risk > 50 else "normal",
            help="KDIGO Criteria"
        )
        
        # 3. Sepsis Score (Red if >= 2)
        s_score = res['sepsis_risk']
        r3.metric(
            "🦠 Sepsis Score", 
            f"{s_score}", 
            "Alert" if s_score >= 2 else "Normal", 
            delta_color="inverse" if s_score >= 2 else "normal",
            help="qSOFA Score"
        )
        
        # 4. Glycemia (Red if High or Low)
        current_gluc = res.get('glucose', 0)
        hypo_risk = res.get('hypo_risk', 0)
        
        if current_gluc > 180:
             r4.metric("🍬 Glycemia", f"{int(current_gluc)} mg/dL", "Hyper (High)", delta_color="inverse")
        elif current_gluc > 0 and current_gluc < 70:
             r4.metric("🍬 Glycemia", f"{int(current_gluc)} mg/dL", "Hypo (Low)", delta_color="inverse")
        else:
             r4.metric(
                 "🍬 Hypo Risk", 
                 f"{hypo_risk}%", 
                 "Normal",
                 delta_color="inverse" if hypo_risk > 50 else "normal"
             )

        # Row 2: Hemodynamics
        h1, h2, h3, h4 = st.columns(4)
        
        # MAP (Red if < 65)
        map_val = int(res.get('map_val', 0))
        h1.metric(
            "MAP", 
            f"{map_val} mmHg", 
            "Low" if map_val < 65 else "Normal",
            delta_color="inverse" if map_val < 65 else "normal",
            help="Mean Arterial Pressure"
        )
        
        # SIRS Score (Red if >= 2)
        sirs = res.get('sirs_score', 0)
        h2.metric(
            "⚡ SIRS Score", 
            f"{sirs}/4", 
            "Alert" if sirs >= 2 else "Normal",
            delta_color="inverse" if sirs >= 2 else "normal",
            help="Inflammatory Response"
        )
        
        # Shock Index (Red if > 0.9)
        si = res.get('shock_index', 0)
        h3.metric(
            "💔 Shock Index", 
            f"{si:.2f}", 
            "Critical" if si > 0.9 else "Normal",
            delta_color="inverse" if si > 0.9 else "normal",
            help="HR / SBP"
        )
        
        # Pulse Pressure (Red if Wide > 60 or Narrow < 25)
        pp = int(res.get('pulse_pressure', 0))
        if pp > 60:
            pp_status = "Wide (>60)"
            pp_color = "inverse"
        elif pp < 25 and pp > 0:
            pp_status = "Narrow (<25)"
            pp_color = "inverse"
        else:
            pp_status = "Normal"
            pp_color = "normal"
            
        h4.metric(
            "💓 Pulse Pressure", 
            f"{pp}", 
            pp_status,
            delta_color=pp_color,
            help="SBP - DBP"
        )

        st.divider()

        # --- EXPLANATION SECTION (UNIFIED & UPGRADED) ---
        with st.expander("🧠 Clinical Logic: Why is this patient Critical?"):
            tab1, tab2, tab3, tab4 = st.tabs(["Bleeding Risk", "AKI Risk", "Sepsis (qSOFA)", "Hemodynamics"])
            
            # --- TAB 1: BLEEDING (UPGRADED with Liver/GI checks) ---
            with tab1:
                st.write("### Factors driving the Bleeding Risk Score:")
                
                # 1. Coagulation
                if res.get('inr', 0) > 3.5: 
                    st.error(f"• **Critical INR ({res.get('inr')}):** Major driver of hemorrhage risk (+40 pts).")
                elif res.get('inr', 0) > 1.2:
                    st.warning(f"• **Elevated INR ({res.get('inr')}):** Contributes to risk.")
                if res.get('anticoag'): 
                    st.warning("• **Anticoagulant Use:** Patient is on blood thinners (+35 pts).")
                
                # 2. Comorbidities (The extra detail you need)
                if res.get('liver_disease'):
                    st.error("• **Liver Disease:** Impaired clotting factors & thrombocytopenia risk.")
                if res.get('gib_input'): 
                     st.error("• **History of GI Bleed:** Strong predictor of recurrence.")
                
                # 3. Vitals & Demographics
                if res.get('sys_bp', 0) > 160:
                    st.warning(f"• **Uncontrolled Hypertension (SBP {res.get('sys_bp')}):** Increases vessel rupture risk.")
                if res.get('age', 0) > 65: 
                    st.info(f"• **Age ({res.get('age')}):** Geriatric fragility factor (+10 pts).")
                
                # 4. Safety Check
                has_risk = (res.get('inr', 0) > 1.5 or res.get('anticoag') or res.get('age', 0) > 65 or 
                           res.get('liver_disease') or res.get('gib_input') or res.get('sys_bp', 0) > 160)
                if not has_risk:
                    st.success("✅ No major bleeding risk factors identified.")

            # --- TAB 2: AKI (Your existing detailed code) ---
            with tab2: 
                st.write("### Factors driving AKI Risk:")
                if res.get('diuretic'): st.warning("• **Diuretic Use:** +30 points")
                if res.get('acei'): st.warning("• **ACEi/ARB Use:** +40 points")
                if res.get('sys_bp', 0) < 90: st.error(f"• **Hypotension (SBP {res.get('sys_bp', 0)}):** +20 points")
                if not (res.get('diuretic') or res.get('acei') or res.get('sys_bp', 0) < 90):
                    st.success("No major nephrotoxic risks identified.")

            # --- TAB 3: SEPSIS (Your existing detailed code) ---
            with tab3: 
                st.write("### Sepsis Assessment (qSOFA Criteria)")
                sepsis_points = 0
                if res.get('resp_rate', 0) >= 22:
                    st.error(f"• **Respiratory Rate ({res.get('resp_rate')}):** +1 Point (Target < 22)")
                    sepsis_points += 1
                if res.get('sys_bp', 0) <= 100:
                    st.error(f"• **Systolic BP ({res.get('sys_bp')}):** +1 Point (Target > 100)")
                    sepsis_points += 1
                if res.get('altered_mental'):
                    st.error("• **Altered Mental Status:** +1 Point")
                    sepsis_points += 1
                if sepsis_points == 0: st.success("Patient meets 0 qSOFA criteria (Low Sepsis Risk).")

            # --- TAB 4: HEMODYNAMICS (Your existing detailed code) ---
            with tab4: 
                st.write("### Hemodynamic Stability Checks")
                current_map = int(res.get('map_val', 0))
                current_si = res.get('shock_index', 0)
                st.write(f"**Mean Arterial Pressure (MAP):** {current_map} mmHg")
                if current_map < 65: st.error("• MAP < 65 mmHg: Critical organ perfusion threat.")
                else: st.success("• MAP > 65 mmHg: Perfusion is adequate.")
                st.write(f"**Shock Index (HR/SBP):** {current_si:.2f}")
                if current_si > 0.9: st.error("• Index > 0.9: High probability of shock.")
                elif current_si > 0.7: st.warning("• Index 0.7 - 0.9: Monitor closely.")
                else: st.success("• Index < 0.7: Hemodynamically stable.")
       
       # --- CLINICAL ALERTS & PROTOCOLS (RESTORED) ---
        st.markdown("### ⚠️ Clinical Alerts & AI Recommendations")
        violations = 0 
        
        # --- A. AIRWAY & BREATHING ---
        if res.get('o2_sat', 0) > 0 and res.get('o2_sat', 0) < 88: 
            st.error(f"🚨 CRITICAL HYPOXIA (SpO2 {res['o2_sat']}%)")
            st.info("👉 **Protocol:** 15L O2 via Non-Rebreather. Prepare for RSI/Intubation. Check ABG.")
            violations += 1
        elif res.get('o2_sat', 0) > 0 and res.get('o2_sat', 0) < 92:
            st.warning(f"⚠️ Hypoxia (SpO2 {res['o2_sat']}%)")
            violations += 1
        
        if res.get('resp_rate', 0) > 30:
            st.error(f"🚨 SEVERE TACHYPNEA (RR {res['resp_rate']})")
            violations += 1
        elif res.get('resp_rate', 0) < 8 and res.get('resp_rate', 0) > 0:
            st.error(f"🚨 RESPIRATORY DEPRESSION (RR {res['resp_rate']})")
            violations += 1

        # --- B. CIRCULATION ---
        if res.get('sys_bp', 0) > 180: 
            st.error(f"🚨 HYPERTENSIVE CRISIS (BP {res['sys_bp']}/{res['dia_bp']})")
            violations += 1
        elif res.get('sys_bp', 0) > 0 and res.get('sys_bp', 0) < 90: 
            st.error(f"🚨 SHOCK / HYPOTENSION (BP {res['sys_bp']}/{res['dia_bp']})")
            st.info("👉 **Protocol:** Trendelenburg position. 500mL Fluid Bolus. Start Norepinephrine if MAP < 65.")
            violations += 1
            
        if res.get('hr', 0) > 130:
            st.error(f"🚨 SEVERE TACHYCARDIA (HR {res['hr']})")
            violations += 1
        elif res.get('hr', 0) > 0 and res.get('hr', 0) < 40:
            st.error(f"🚨 SEVERE BRADYCARDIA (HR {res['hr']})")
            violations += 1

        # --- C. DISABILITY / EXPOSURE ---
        if res.get('temp_c', 0) > 39.0:
             st.error(f"🚨 HIGH FEVER ({res['temp_c']}°C)")
             violations += 1
        elif res.get('temp_c', 0) < 35.0 and res.get('temp_c', 0) > 0:
             st.error(f"🚨 HYPOTHERMIA ({res['temp_c']}°C)")
             violations += 1

        # --- D. CRITICAL LABS ---
        if res.get('glucose', 0) > 400:
            st.error(f"🚨 SEVERE HYPERGLYCEMIA ({res['glucose']} mg/dL)")
            violations += 1
        elif res.get('glucose', 0) > 0 and res.get('glucose', 0) < 70:
            st.error(f"🚨 HYPOGLYCEMIA ({res['glucose']} mg/dL)")
            st.info("👉 **Protocol:** D50 IV Push or Glucagon IM immediately. Recheck glucose in 15 mins.")
            violations += 1

        if res.get('potassium', 0) > 6.0:
            st.error(f"🚨 CRITICAL HYPERKALEMIA (K+ {res['potassium']})")
            violations += 1
        elif res.get('potassium', 0) > 0 and res.get('potassium', 0) < 2.5:
            st.error(f"🚨 CRITICAL HYPOKALEMIA (K+ {res['potassium']})")
            violations += 1
            
        if res.get('lactate', 0) >= 4.0: 
            st.error(f"🚨 SEVERE LACTIC ACIDOSIS ({res['lactate']} mmol/L)")
            st.info("👉 **Protocol:** Aggressive IV fluids (30mL/kg). Draw Blood Cultures. Start Broad-Spectrum Antibiotics.")
            violations += 1
        
        # --- Check for missing data (optional) ---
        has_demographics = (res.get('age', 0) > 0 or res.get('weight', 0) > 0)
        has_vitals = (res.get('sys_bp', 0) > 0 or res.get('hr', 0) > 0)

        if violations == 0:
            if not has_demographics and not has_vitals:
                st.warning("⚠️ **No Data Entered:** Please input patient data to run analysis.")
            elif has_demographics and not has_vitals:
                st.warning("⚠️ **Missing Vitals:** Demographics recorded, but Vital Signs (BP, HR, SpO2) are required to determine stability.")
            else:
                st.success("✅ **Patient Stable:** No immediate life-threatening protocol violations detected.")
        
        st.divider()
        
        # --- AI CONSULT BUTTON ---
        c_ai, c_txt = st.columns([1, 3])
        with c_ai:
            st.markdown("#### 🤖 AI Assessment")
            if st.button("⚡ Consult AI"):
                with st.spinner("Thinking..."):
                    ai_context = {
                        'age': res['age'], 'sbp': res['sys_bp'], 
                        'bleeding_risk': res['bleeding_risk'], 'aki_risk': res['aki_risk'],
                        'shock_index': res['shock_index']
                    }
                    response = bk.consult_ai_doctor("risk_assessment", "", ai_context)
                    st.session_state['ai_result'] = response
        with c_txt:
            if 'ai_result' in st.session_state: st.info(st.session_state['ai_result'])
            else: st.info("👈 Fill out the patient data form above and click 'Run Clinical Analysis' to see results.")
                
        st.divider()
        st.subheader("🖨️ Export Reports")
        
        # This button generates the PDF using the function we added to the top
        if st.button("📄 Generate PDF Clinical Report"):
            # Get the AI result if it exists, otherwise leave blank
            ai_text = st.session_state.get('ai_result', "No AI consult run.")
            
            # Create the PDF
            pdf_bytes = create_pdf_report(res, ai_text)
            
            # Create a download link (Magic Streamlit trick)
            b64 = base64.b64encode(pdf_bytes).decode()
            href = f'<a href="data:application/octet-stream;base64,{b64}" download="Patient_Report_{res.get("age")}yo.pdf" style="text-decoration:none;">' \
                   f'<button style="background-color:#FF4B4B;color:white;border:none;padding:10px 20px;border-radius:5px;cursor:pointer;">' \
                   f'⬇️ Download PDF File Now</button></a>'
            
            st.success("✅ PDF Generated successfully!")
            st.markdown(href, unsafe_allow_html=True)
                

# --- MODULE 2: PATIENT HISTORY---
def render_history_sql():
    st.subheader("🗄️ Patient History Database")
    
    # Fetch Data
    df = bk.fetch_history()
    
    if not df.empty:
        # 1. Format the DataFrame for Display
        if 'timestamp' in df.columns:
            df['timestamp'] = pd.to_datetime(df['timestamp']).dt.strftime('%Y-%m-%d %H:%M')

        # 2. Styling Helper
        def highlight_risk(val):
            if isinstance(val, (int, float)):
                if val > 50: return 'background-color: #ffcdd2; color: black;' # Red
                if val > 20: return 'background-color: #fff9c4; color: black;' # Yellow
            return ''

        # 3. Configure Columns
        st.dataframe(
            df,
            column_config={
                "timestamp": st.column_config.TextColumn("📅 Date & Time", width="medium"),
                "age": st.column_config.NumberColumn("👤 Age", format="%d yrs"),
                "gender": st.column_config.TextColumn("⚧ Gender", width="small"),
                "sbp": st.column_config.NumberColumn("❤️ SBP", format="%d mmHg"),
                "aki_risk_score": st.column_config.ProgressColumn(
                    "💧 AKI Risk", 
                    format="%d%%", 
                    min_value=0, 
                    max_value=100,
                    help="Acute Kidney Injury Probability"
                ),
                "bleeding_risk_score": st.column_config.ProgressColumn(
                    "🩸 Bleed Risk", 
                    format="%.1f%%", 
                    min_value=0, 
                    max_value=100,
                    help="Hemorrhage Risk Score"
                ),
                "status": st.column_config.TextColumn("🏥 Status"),
            },
            use_container_width=True,
            height=400,
            hide_index=True
        )

        st.divider()
        
        # 4. Analytics Section
        st.markdown("### 📈 Cohort Analytics")
        c1, c2 = st.columns(2)
        
        with c1:
            st.caption("Risk Distribution by Age")
            st.scatter_chart(df, x='age', y='bleeding_risk_score', color='status', height=250)
            
        with c2:
            st.caption("Average Vitals Trend")
            if len(df) > 1:
                st.line_chart(df.set_index('timestamp')['sbp'], height=250)
            else:
                st.info("Need more data for trend analysis.")

        # 5. Admin Actions
        with st.expander("⚙️ Database Management"):
            if st.button("🗑️ Clear All Records", type="secondary"):
                bk.clear_history()
                st.rerun()
    else:
        st.info("📭 Database is empty. Run a Risk Analysis to create records.")

# --- MODULE 3: LIVE DASHBOARD (LINKED TO CALCULATOR) ---
def render_dashboard():
    # 1. GET DATA FROM SESSION STATE
    data = st.session_state.get('patient_data', {})
    
    # Default values if no analysis has been run yet
    if not data:
        st.warning("⚠️ No patient data found. Please run the Risk Calculator first.")
        return

    is_critical = data.get('status') == 'Critical'
    
    # --- HEADER & AI BUTTON ---
    c1, c2 = st.columns([3, 1])
    with c1:
        st.subheader(f"🛏️ Bedside Monitor: {data.get('id', 'Unknown')}")
        st.caption(f"Status: **{data.get('status', 'Unknown')}**")
    
    with c2:
        # AI DISCHARGE SUMMARY
        if st.button("✨ Generate Discharge Note", type="primary"):
            with st.spinner("Consulting Gemini 2.0..."):
                ai_summary = bk.generate_discharge_summary(data)
                st.session_state['latest_discharge_note'] = ai_summary
        
        # --- Timestamped Download ---
        if 'latest_discharge_note' in st.session_state:
            st.download_button(
                label="📥 Download Note",
                data=st.session_state['latest_discharge_note'],
                file_name=f"discharge_{data.get('id')}_{get_timestamp()}.txt",
                mime="text/plain"
            )
            
    # --- PREVIEW AREA (View Generated Summary) ---
    if 'latest_discharge_note' in st.session_state:
        with st.expander("📄 View Generated Summary", expanded=True):
            st.text_area("Edit before downloading:", value=st.session_state['latest_discharge_note'], height=200)

    st.divider()

    # --- REAL-TIME VITALS PANEL (Uses Real Inputs) ---
    with st.container(border=True):
        st.markdown("#### 📉 Real-Time Telemetry")
        
        st.caption("ℹ️ Note: Telemetry trace below is simulated based on static input data for UI demonstration.")
        
        col_chart, col_vitals = st.columns([3, 1])
        
        with col_chart:
            # Simulate a live trace based on the INPUT BP and HR
            base_sbp = data.get('sys_bp', 120)
            base_hr = data.get('hr', 80)
            
            chart_data = pd.DataFrame({
                'Time': range(20),
                'Systolic BP': np.random.normal(base_sbp, 2, 20),
                'Heart Rate': np.random.normal(base_hr, 2, 20)    
            }).melt('Time', var_name='Metric', value_name='Value')
            
            c = alt.Chart(chart_data).mark_line(interpolate='basis', strokeWidth=3).encode(
                x=alt.X('Time', axis=None),
                y=alt.Y('Value', scale=alt.Scale(zero=False)),
                color=alt.Color('Metric', scale=alt.Scale(range=['#FF4B4B', '#00CC96']))
            ).properties(height=200)
            
            st.altair_chart(c, use_container_width=True)

        with col_vitals:
            st.markdown(f"""
            <div style="background-color:#0E1117; padding:15px; border-radius:10px; text-align:center; border: 1px solid #333;">
                <h3 style="color:#FF4B4B; margin:0;">{int(data.get('sys_bp', 0))}</h3>
                <p style="color:gray; font-size:12px; margin:0;">mmHg (SBP)</p>
                <hr style="margin: 10px 0; border-color:#333;">
                <h3 style="color:#00CC96; margin:0;">{int(data.get('hr', 0))}</h3>
                <p style="color:gray; font-size:12px; margin:0;">BPM (HR)</p>
                <hr style="margin: 10px 0; border-color:#333;">
                <h3 style="color:#00A6ED; margin:0;">{int(data.get('o2_sat', 0))}%</h3>
                <p style="color:gray; font-size:12px; margin:0;">SpO2</p>
            </div>
            """, unsafe_allow_html=True)

    # --- RISK METRICS (From Analysis) ---
    st.markdown("#### ⚠️ Risk Stratification")
    r1, r2, r3, r4 = st.columns(4)
    
    r1.metric("🩸 Bleeding Risk", f"{data.get('bleeding_risk', 0):.1f}%", 
              "High" if data.get('bleeding_risk', 0) > 50 else "Normal", delta_color="inverse",
              help="Probability of major hemorrhage based on XGBoost model.")
    
    r2.metric("💧 AKI Risk", f"{data.get('aki_risk', 0)}%", 
              "Critical" if data.get('aki_risk', 0) > 50 else "Normal", delta_color="inverse",
              help="Acute Kidney Injury Risk based on KDIGO criteria.")
    
    r3.metric("🦠 Sepsis Score", f"{data.get('sepsis_risk', 0)}", 
              "Alert" if data.get('sepsis_risk', 0) >= 2 else "Normal", delta_color="inverse",
              help="qSOFA Score (0-3). ≥2 indicates high sepsis risk.")
    
    r4.metric("🌡️ Temp", f"{data.get('temp_c', 37.0):.1f}°C", "Fever" if data.get('temp_c', 37) > 38 else "Normal", delta_color="inverse")

# --- MODULE 4: BATCH ANALYSIS (SMART VALIDATION & NEWS-2) ---
def render_batch_analysis():
    st.subheader("Bulk Patient Processing & Diagnostic Triage")
    
    # 1. Helper: Download Template
    with st.expander("ℹ️  Download CSV Template"):
        sample_data = {
            'Age': [65, 72], 'Gender': ['Male', 'Female'], 'Weight_kg': [80, 65],
            'Systolic_BP': [130, 90], 'Diastolic_BP': [80, 50], 'Heart_Rate': [72, 110],
            'Resp_Rate': [16, 24], 'Temp_C': [37.0, 38.5], 'O2_Sat': [98, 92],
            'WBC': [6.0, 15.0], 'Glucose': [110, 5.5], 'Creatinine': [1.1, 150],
            'INR': [1.0, 1.2], 'Altered_Mental': [0, 1], 'Anticoagulant': [1, 0],
            'Heart_Failure': [0, 1], 'Liver_Disease': [0, 0], 'Hx_GI_Bleed': [0, 0]
        }
        df_sample = pd.DataFrame(sample_data)
        csv_template = df_sample.to_csv(index=False).encode('utf-8')
        st.download_button("📥 Download Template", csv_template, "patient_data.csv", "text/csv")

    # 2. CSV PROCESSOR
    st.markdown("#### 📤 Upload Patient Batch")
    uploaded_csv = st.file_uploader("Upload Patient Data (CSV)", type=["csv"])
    
    if uploaded_csv:
        try:
            raw_df = pd.read_csv(uploaded_csv)
            
            # --- A. SMART MAPPING ---
            col_map = {
                'sbp':'Systolic_BP', 'sys':'Systolic_BP', 'hr':'Heart_Rate', 'rr':'Resp_Rate', 'temp':'Temp_C',
                'spo2':'O2_Sat', 'cr':'Creatinine', 'wbc':'WBC', 'glu':'Glucose', 'sugar':'Glucose'
            }
            df = raw_df.rename(columns=lambda x: col_map.get(x.lower(), x))
            
            # Fill missing with safe defaults for calculation
            req_cols = ['Age','Systolic_BP','Heart_Rate','Resp_Rate','Temp_C','O2_Sat','Creatinine','Glucose']
            for c in req_cols:
                if c not in df.columns: df[c] = 0

            if st.button("⚡ Run Clinical Analysis", type="primary"):
                with st.spinner("Validating Data & Calculating Risks..."):
                    
                    # --- B. SMART UNIT CONVERSION & VALIDATION ---
                    def clean_row(row):
                        # 1. Glucose: Convert mmol/L to mg/dL
                        if 0 < row['Glucose'] < 30:
                            row['Glucose'] = row['Glucose'] * 18
                        
                        # 2. Creatinine: Convert umol/L to mg/dL
                        if row['Creatinine'] > 20:
                            row['Creatinine'] = row['Creatinine'] / 88.4
                            
                        return row
                    
                    df = df.apply(clean_row, axis=1)

                    # --- C. ADVANCED SCORING (NEWS-2) ---
                    def calculate_news(row):
                        score = 0
                        # Resp Rate
                        if row['Resp_Rate'] <= 8 or row['Resp_Rate'] >= 25: score += 3
                        elif row['Resp_Rate'] >= 21: score += 2
                        elif row['Resp_Rate'] <= 11: score += 1
                        
                        # SpO2
                        if row['O2_Sat'] <= 91: score += 3
                        elif row['O2_Sat'] <= 93: score += 2
                        elif row['O2_Sat'] <= 95: score += 1
                        
                        # Systolic BP
                        if row['Systolic_BP'] <= 90 or row['Systolic_BP'] >= 220: score += 3
                        elif row['Systolic_BP'] <= 100: score += 2
                        elif row['Systolic_BP'] <= 110: score += 1
                        
                        # Heart Rate
                        if row['Heart_Rate'] <= 40 or row['Heart_Rate'] >= 131: score += 3
                        elif row['Heart_Rate'] >= 111: score += 2
                        elif row['Heart_Rate'] <= 50 or row['Heart_Rate'] >= 91: score += 1
                        
                        # Consciousness
                        if row.get('Altered_Mental', 0) == 1: score += 3
                        
                        # Temp
                        if row['Temp_C'] <= 35.0: score += 3
                        elif row['Temp_C'] >= 39.1: score += 2
                        elif row['Temp_C'] <= 36.0 or row['Temp_C'] >= 38.1: score += 1
                        
                        return score

                    df['NEWS_Score'] = df.apply(calculate_news, axis=1)

                    # --- D. DIAGNOSTIC LABELS ---
                    def get_status(row):
                        alerts = []
                        # 1. NEWS-2 Interpretation
                        if row['NEWS_Score'] >= 7: alerts.append("CRITICAL (NEWS ≥7)")
                        elif row['NEWS_Score'] >= 5: alerts.append("Urgent (NEWS ≥5)")
                        
                        # 2. Specific Organ Failures
                        if row['Systolic_BP'] > 180: alerts.append("HTN Crisis")
                        if row['Creatinine'] > 2.0: alerts.append("AKI Warning")
                        if row.get('WBC', 0) > 12: alerts.append("Leukocytosis")
                        
                        return " + ".join(alerts) if alerts else "Stable"

                    df['Clinical_Status'] = df.apply(get_status, axis=1)
                    
                    # Run AI Prediction (Create simple input df for the XGBoost model)
                    model_inputs = pd.DataFrame()
                    model_inputs['age'] = df.get('Age', 0)
                    model_inputs['inr'] = df.get('INR', 1.0)
                    model_inputs['anticoagulant'] = df.get('Anticoagulant', 0)
                    model_inputs['gi_bleed'] = df.get('Hx_GI_Bleed', 0)
                    model_inputs['high_bp'] = df['Systolic_BP'].apply(lambda x: 1 if x > 140 else 0)
                    model_inputs['antiplatelet'] = 0
                    model_inputs['gender_female'] = 0 
                    model_inputs['weight'] = df.get('Weight_kg', 70)
                    model_inputs['liver_disease'] = df.get('Liver_Disease', 0)
                    
                    df['Bleed_Risk_%'] = bleeding_model.predict(model_inputs)

                    # --- E. DISPLAY ---
                    def color_rows(val):
                        if 'CRITICAL' in str(val): return 'background-color: #ffcdd2; color: black; font-weight: bold;'
                        if 'Urgent' in str(val) or 'Warning' in str(val): return 'background-color: #fff3cd; color: black;'
                        return ''

                    st.success(f"Processed {len(df)} records with enhanced validation.")
                    st.dataframe(
                        df[['Clinical_Status', 'NEWS_Score', 'Age', 'Systolic_BP', 'Bleed_Risk_%']]
                        .style.map(color_rows, subset=['Clinical_Status']), 
                        use_container_width=True
                    )
                    
                    # ---Timestamped Download ---
                    csv_result = df.to_csv(index=False).encode('utf-8')
                    st.download_button(
                        "📥 Download Analyzed Data", 
                        csv_result, 
                        f"analyzed_patients_{get_timestamp()}.csv", 
                        "text/csv"
                    )
                
        except Exception as e:
            st.error(f"Error processing CSV: {e}")

# --- MODULE 5: MEDICATION CHECKER ---
def render_medication_checker():
    st.subheader("💊 Drug-Drug Interaction Checker")
    st.caption("Checks for Critical and Major interactions from backend database + AI Analysis.")
    
    col_d1, col_d2 = st.columns(2)
    d1 = col_d1.text_input("Drug A", placeholder="e.g. Warfarin")
    d2 = col_d2.text_input("Drug B", placeholder="e.g. Ibuprofen")

    if d1 and d2:
        st.divider()
        
        # 1. Database Check (Deterministic)
        res = bk.check_interaction(d1, d2)
        
        if res:
            if "CRITICAL" in res: 
                st.error(f"❌ {res}")
            elif "MAJOR" in res: 
                st.warning(f"⚠️ {res}")
            elif "MODERATE" in res: 
                st.info(f"ℹ️ {res}")
        else: 
            st.warning(f"⚠️ **{d1}** + **{d2}** not found in the high-alert database.")
            st.markdown("👉 **Recommendation:** This does not guarantee safety. Please use the **AI Pharmacist** below for a comprehensive check.")

        # 2. AI Analysis Button
        st.divider()
        st.markdown("#### 🧠 AI Pharmacist Analysis")
        st.caption("Get a detailed explanation of mechanism, management, and safety profile.")
        
        if st.button("⚡ Analyze Interaction with AI"):
            with st.spinner("Consulting AI Pharmacist..."):
                ai_report = bk.analyze_drug_interactions([d1, d2])
                st.markdown(ai_report)
                st.caption("⚠️ AI-Generated. Verify with standard drug compendiums.")

# --- MODULE 6: CHATBOT ---
def render_chatbot():
    st.subheader("AI Clinical Assistant")
    st.caption("Database covers 250+ clinical topics (Cardio, Resp, Neuro, Pharm, Labs).")
    
    q = st.text_input("Ask a clinical question:")
    if q:
        with st.chat_message("assistant"):
            st.write(bk.chatbot_response(q))

# --- MODULE 7: AI DIAGNOSTICIAN ---
def render_ai_diagnostician():
    st.subheader("🧠 AI-Powered Clinical Consultant")
    st.caption("Ask complex clinical questions or simulate differential diagnoses.")
    
    # Initialize Chat History
    if "messages" not in st.session_state:
        st.session_state["messages"] = [{"role": "assistant", "content": "Hello! I am your AI Clinical Consultant. Describe a patient case or ask a medical question."}]

    # Display History
    for msg in st.session_state.messages:
        st.chat_message(msg["role"]).write(msg["content"])

    # Chat Input
    if prompt := st.chat_input("Type your clinical query here..."):
        # 1. User Message
        st.session_state.messages.append({"role": "user", "content": prompt})
        st.chat_message("user").write(prompt)
        
        # 2. AI Response
        with st.spinner("Thinking..."):
            # Get context from session if available
            current_data = st.session_state.get('patient_data', {})
            
            # Call Backend
            response = bk.consult_ai_doctor("provider", prompt, current_data)
            
            # 3. Display AI Message
            st.session_state.messages.append({"role": "assistant", "content": response})
            st.chat_message("assistant").write(response)

# ---------------------------------------------------------
# 3. MAIN APP CONTROLLER
# ---------------------------------------------------------
if not st.session_state['entered_app']:
    render_cover_page()
else:
    with st.sidebar:
        st.title("Navigation")
        menu = st.radio("Select Module", [
            "Risk Calculator", 
            "Patient History (SQL)",
            "Live Dashboard", 
            "Batch Analysis (CSV)", 
            "Medication Checker", 
            "📚 Medical Glossary",
            "🧠 AI Clinical Consultant"
        ])
        st.info("v3.0 - AI Integrated")

    if menu == "Risk Calculator":
        render_risk_calculator()
    elif menu == "Patient History (SQL)":
        render_history_sql()
    elif menu == "Live Dashboard":
        render_dashboard()
    elif menu == "Batch Analysis (CSV)":
        render_batch_analysis()
    elif menu == "Medication Checker":
        render_medication_checker()
    elif menu == "📚 Medical Glossary":
        render_chatbot()
    elif menu == "🧠 AI Clinical Consultant":
        render_ai_diagnostician()
      # ---------------------------------------------------------
    # DEBUG: ADMIN PANEL (Only visible if URL has ?admin=true)
    # ---------------------------------------------------------
    # Check if the URL is https://.../?admin=true
    if "admin" in st.query_params: 
        st.sidebar.divider()
        st.sidebar.subheader("🔧 Admin Mode")
        if st.sidebar.button("⚡ Force Retrain Model"):
            with st.spinner("Training new model on Cloud Server..."):
                try:
                    import train_model
                    train_model.train()
                    st.success("✅ Model Retrained! Reboot App now.")
                except Exception as e:
                    st.error(f"Failed: {e}")
