# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lgDqGUkYjjSXMelXU7E8iHmtTQQy1j09
"""
import streamlit as st
import pandas as pd
import numpy as np
import xgboost as xgb
import os

# ---------------------------------------------------------
# 1. PAGE CONFIGURATION
# ---------------------------------------------------------
st.set_page_config(
    page_title="Clinical Risk Monitor",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ---------------------------------------------------------
# 2. LOAD AI MODEL
# ---------------------------------------------------------
@st.cache_resource
def load_bleeding_model():
    """Loads the pre-trained XGBoost model."""
    model = xgb.XGBRegressor()
    model_file = "bleeding_risk_model.json"

    if not os.path.exists(model_file):
        st.error(f"⚠️ CRITICAL ERROR: '{model_file}' not found.")
        st.info("💡 To fix: Run 'train_model.py' locally first.")
        st.stop()

    model.load_model(model_file)
    return model

try:
    bleeding_model = load_bleeding_model()
except Exception as e:
    st.error(f"Model failed to load: {e}")
    st.stop()

# ---------------------------------------------------------
# 3. CLINICAL LOGIC ENGINES
# ---------------------------------------------------------

# A. AKI Risk (Kidney)
def calculate_aki_risk(age, diuretic, acei, high_bp, chemo, creat, contrast):
    score = 0
    score += 30 if diuretic else 0
    score += 40 if acei else 0
    score += 25 if contrast else 0
    score += 20 if age > 75 else 0
    score += 10 if high_bp else 0
    score += 20 if chemo else 0
    if creat > 1.5: score += 30
    elif creat > 1.2: score += 15
    return min(score, 100)

# B. Hypoglycemic Risk (Blood Sugar) - RESTORED
def calculate_hypoglycemic_risk(insulin, renal, hba1c_high, neuropathy, recent_dka):
    score = 0
    score += 30 if insulin else 0
    score += 45 if renal else 0
    score += 20 if hba1c_high else 0
    score += 10 if neuropathy else 0
    score += 20 if recent_dka else 0
    return min(score, 100)

# C. Comorbidity Load (Frailty) - RESTORED
def calculate_comorbidity_load(prior_stroke, active_chemo, liver_disease, high_bp):
    load = 0
    load += 25 if prior_stroke else 0
    load += 30 if active_chemo else 0
    load += 15 if liver_disease else 0
    load += 10 if high_bp else 0
    return min(load, 100)

# D. Interaction Database
interaction_db = {
    ("warfarin", "amiodarone"): "MAJOR: Amiodarone increases INR significantly. Reduce Warfarin dose by 30-50%.",
    ("warfarin", "ibuprofen"): "MAJOR: NSAIDs increase bleeding risk and damage gastric mucosa.",
    ("lisinopril", "spironolactone"): "MAJOR: Risk of severe hyperkalemia (high potassium). Monitor K+.",
    ("sildenafil", "nitroglycerin"): "CRITICAL: Fatal hypotension. Contraindicated.",
    ("methotrexate", "trimethoprim"): "CRITICAL: Bone marrow toxicity. Avoid.",
    ("simvastatin", "amiodarone"): "MAJOR: Rhabdomyolysis risk. Simvastatin dose should not exceed 20mg.",

    # --- NEW ADDITIONS (20+ High-Impact Checks) ---
    
    # 1. THE "SILENT KILLERS" (Hyperkalemia & Arrhythmia)
    ("spironolactone", "trimethoprim"): "CRITICAL: High risk of sudden death from Hyperkalemia (Spironolactone + Bactrim).",
    ("ciprofloxacin", "ondansetron"): "MAJOR: QT Prolongation risk. Monitor ECG.",
    ("levofloxacin", "ondansetron"): "MAJOR: QT Prolongation risk. Monitor ECG.",
    ("citalopram", "fluconazole"): "MAJOR: QT Prolongation risk. Avoid high doses.",
    
    # 2. RESPIRATORY DEPRESSION (Black Box Warnings)
    ("oxycodone", "lorazepam"): "CRITICAL: Respiratory depression/Sedation risk (Opioid + Benzo).",
    ("hydrocodone", "alprazolam"): "CRITICAL: Respiratory depression/Sedation risk (Opioid + Benzo).",
    ("fentanyl", "midazolam"): "CRITICAL: Severe respiratory depression.",
    
    # 3. BLEEDING RISKS (Beyond Warfarin)
    ("warfarin", "ciprofloxacin"): "MAJOR: Antibiotics kill gut flora, spiking INR. Monitor closely.",
    ("warfarin", "fluconazole"): "MAJOR: Fluconazole inhibits CYP2C9, dramatically raising INR.",
    ("warfarin", "acetaminophen"): "MODERATE: High/Chronic Tylenol use can elevate INR.",
    ("clopidogrel", "omeprazole"): "MAJOR: Omeprazole blocks CYP2C19, making Plavix ineffective.",
    
    # 4. SEROTONIN SYNDROME (Agitation, Seizures, High Fever)
    ("tramadol", "fluoxetine"): "MAJOR: Risk of Serotonin Syndrome and Seizures.",
    ("sertraline", "linezolid"): "CRITICAL: Linezolid is an MAOI. Fatal Serotonin Syndrome risk.",
    ("cyclobenzaprine", "duloxetine"): "MODERATE: Increased risk of Serotonin Syndrome.",
    
    # 5. TOXICITY & ABSORPTION FAILURES
    ("lithium", "lisinopril"): "MAJOR: ACE Inhibitors reduce Lithium excretion -> Lithium Toxicity.",
    ("lithium", "ibuprofen"): "MAJOR: NSAIDs reduce Lithium excretion -> Lithium Toxicity.",
    ("digoxin", "clarithromycin"): "MAJOR: Macrolides block P-gp -> Digoxin Toxicity.",
    ("levothyroxine", "calcium"): "MODERATE: Calcium blocks Thyroid absorption. Separate by 4 hours.",
    ("doxycycline", "iron"): "MODERATE: Iron binds to antibiotic, causing treatment failure.",
    
    # 6. NEUROLOGICAL RISKS
    ("phenytoin", "oral contraceptives"): "MAJOR: Phenytoin induces enzymes, causing contraceptive failure.",
    ("carbamazepine", "erythromycin"): "MAJOR: Erythromycin increases Carbamazepine levels (Toxicity).",
}

def check_interaction(d1, d2):
    d1, d2 = d1.lower().strip(), d2.lower().strip()
    if (d1, d2) in interaction_db: return interaction_db[(d1, d2)]
    if (d2, d1) in interaction_db: return interaction_db[(d2, d1)]
    return "✅ No high-alert interaction found."

# E. Chatbot Logic
def chatbot_response(text):
    text = text.lower()
    
    # --- DISEASE & CONDITION DEFINITIONS (New) ---
    conditions = {
        "sepsis": "Sepsis is a life-threatening response to infection. Watch for: Fever, Hypotension, Tachycardia, Confusion (qSOFA score).",
        "pneumonia": "Infection inflaming air sacs. Symptoms: Cough with phlegm, fever, chills, difficulty breathing.",
        "heart failure": "CHF occurs when the heart doesn't pump blood as well as it should. Watch for: Edema, Dyspnea, Fatigue.",
        "copd": "Chronic Obstructive Pulmonary Disease. Chronic inflammatory lung disease obstructing airflow. key: Smoking history.",
        "afib": "Atrial Fibrillation: Irregular, rapid heart rate. Risk of Stroke. Treatment often involves anticoagulants (Warfarin/Eliquis).",
        "stroke": "CVA (Stroke) is a medical emergency. BE-FAST: Balance, Eyes, Face, Arms, Speech, Time.",
        "dvt": "Deep Vein Thrombosis: Blood clot in a deep vein (leg). Symptoms: Swelling, pain, warmth, redness.",
        "pe": "Pulmonary Embolism: Blockage in lung artery. Symptoms: Sudden shortness of breath, chest pain, cough.",
        "anemia": "Lack of healthy red blood cells. Symptoms: Fatigue, weakness, pale skin, irregular heartbeats.",
        "gout": "Form of arthritis characterized by severe pain/redness in joints (often big toe). High Uric Acid.",
        "uti": "Urinary Tract Infection. Symptoms: Urge to urinate, burning sensation, cloudy urine.",
        "gerd": "Gastroesophageal Reflux Disease. Stomach acid flows back into the esophagus. Symptom: Heartburn.",
        "migraine": "Severe throbbing headache, often with nausea and sensitivity to light/sound.",
        "osteoporosis": "Bone disease causing bones to become weak/brittle. Risk of fractures.",
        "cirrhosis": "Late-stage scarring (fibrosis) of the liver. Causes: Hepatitis, Alcohol.",
        "pancreatitis": "Inflammation of the pancreas. Symptoms: Upper abdominal pain, nausea, vomiting.",
        "cellulitis": "Bacterial skin infection. Symptoms: Red, swollen, painful skin, warm to the touch.",
        "hypothyroidism": "Underactive thyroid. Symptoms: Fatigue, weight gain, cold sensitivity.",
        "hyperthyroidism": "Overactive thyroid. Symptoms: Weight loss, rapid heartbeat, sweating.",
        "asthma": "Airways narrow and swell/produce extra mucus. Symptoms: Wheezing, shortness of breath."
    }

    # --- EXISTING LOOKUPS ---
    if "inr" in text: return "High INR (>3.5) indicates bleeding risk. Target is 2.0-3.0 for most indications."
    if "metformin" in text: return "Hold Metformin before contrast if eGFR < 30 (Lactic Acidosis risk)."
    if "hypoglycemia" in text: return "Symptoms: Sweating, confusion, tachycardia. Protocol: 'Rule of 15' (15g carbs, wait 15 mins)."
    if "creatinine" in text: return "Serum Creatinine rise of >0.3 mg/dL within 48h indicates Acute Kidney Injury (AKI)."
    if "hyperkalemia" in text: return "High Potassium (>5.5). Risk of fatal arrhythmia. Common cause: ACEi + Spironolactone."
    
    # Search the new Dictionary
    for condition, definition in conditions.items():
        if condition in text:
            return f"**{condition.title()}**: {definition}"
            
    return "I didn't recognize that term. Try asking about 'Sepsis', 'Afib', 'Hypoglycemia', or specific drugs."

# ---------------------------------------------------------
# 4. SESSION STATE
# ---------------------------------------------------------
if 'patient_data' not in st.session_state:
    st.session_state['patient_data'] = {
        'id': 'Room 101', 'age': 65, 'bleeding_risk': 12.5,
        'aki_risk': 10, 'hypo_risk': 5, 'status': 'Stable'
    }

if 'entered_app' not in st.session_state:
    st.session_state['entered_app'] = False

# ---------------------------------------------------------
# 5. UI LAYOUT
# ---------------------------------------------------------

# --- COVER PAGE ---
if not st.session_state['entered_app']:
    st.markdown("<h1 style='text-align: center;'>🛡️ Clinical Risk Monitor</h1>", unsafe_allow_html=True)
    st.markdown("<p style='text-align: center;'>AI-Driven Pharmacovigilance System</p>", unsafe_allow_html=True)
    st.write("")
    c1, c2, c3 = st.columns([1, 2, 1])
    if c2.button("🚀 Launch Dashboard", use_container_width=True, type="primary"):
        st.session_state['entered_app'] = True
        st.rerun()

# --- MAIN APP ---
else:
    with st.sidebar:
        st.title("Navigation")
        menu = st.radio("Select Module", [
            "Live Dashboard",
            "Risk Calculator",
            "Batch Analysis (CSV)", # RESTORED
            "Medication Checker",
            "Clinical Chatbot"
        ])
        st.info("v2.1 - Full Integrated Build")

    # --- MODULE 1: LIVE DASHBOARD ---
    if menu == "Live Dashboard":
        data = st.session_state['patient_data']
        st.subheader(f"🏥 Patient Monitor: {data['id']}")

        # Metrics Row
        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Patient Age", f"{data['age']} yrs")
        c2.metric("Bleeding Risk", f"{data['bleeding_risk']:.1f}%", "High" if data['bleeding_risk']>50 else "Normal")
        c3.metric("AKI Risk", f"{data['aki_risk']}%", "Critical" if data['aki_risk']>70 else "Normal")
        c4.metric("Hypo Risk", f"{data['hypo_risk']}%", "High" if data['hypo_risk']>50 else "Low")

        st.divider()

        # Split Layout: Charts vs Queue
        col_main, col_queue = st.columns([2, 1])

        with col_main:
            st.markdown("#### 📈 Real-Time Vitals & Risk Trend")
            chart_data = pd.DataFrame({
                'Hour': [1,2,3,4,5],
                'Risk Score': [data['bleeding_risk']*0.8, data['bleeding_risk']*0.9, data['bleeding_risk'], data['bleeding_risk']*1.1, data['bleeding_risk']]
            })
            st.line_chart(chart_data.set_index('Hour'))

            # Alerts Area
            st.markdown("#### ⚠️ Clinical Alerts")
            if data['bleeding_risk'] > 50:
                st.error("HIGH BLEED RISK: Review Anticoagulants immediately.")
            elif data['aki_risk'] > 50:
                st.warning("RENAL ALERT: Monitor Urine Output & Creatinine.")
            elif data['hypo_risk'] > 50:
                st.warning("METABOLIC ALERT: Risk of Hypoglycemia.")
            else:
                st.success("No Critical Alerts Active.")

        with col_queue:
            st.markdown("#### 📋 Patient Queue (Simulated)")
            # RESTORED PATIENT QUEUE VISUALS
            st.markdown(f"""
            <div style="background-color:#d4edda; color:#155724; padding:10px; border-radius:5px; margin-bottom:10px;">
                <strong>{data['id']} (Current)</strong><br>Status: {data['status']}
            </div>
            """, unsafe_allow_html=True)

            st.markdown("""
            <div style="background-color:#fff3cd; color:#856404; padding:10px; border-radius:5px; margin-bottom:10px;">
                <strong>Patient B (Room 410)</strong><br>🟠 Risk: 80% (AKI Focus)
            </div>
            <div style="background-color:#f8d7da; color:#721c24; padding:10px; border-radius:5px;">
                <strong>Patient C (Room 105)</strong><br>🔴 Risk: 92% (Sepsis)
            </div>
            """, unsafe_allow_html=True)

    # --- MODULE 2: CALCULATOR ---
# --- MODULE 2: CALCULATOR (EXPANDED) ---
    elif menu == "Risk Calculator":
        st.subheader("Acute Risk Calculator (Hybrid AI + Rules)")
        
        with st.form("risk_form"):
            # 1. Demographics
            st.markdown("#### 1. Patient Profile")
            c1, c2, c3 = st.columns(3)
            age = c1.number_input("Age", 18, 100, 65)
            gender = c2.selectbox("Gender", ["Male", "Female"])
            weight = c3.number_input("Weight (kg)", 40, 150, 70)
            
            # 2. Labs
            st.markdown("#### 2. Labs & Vitals")
            c4, c5, c6 = st.columns(3)
            creat = c4.number_input("Creatinine", 0.5, 10.0, 1.0)
            inr = c5.number_input("INR", 0.0, 10.0, 2.5)
            hba1c_high = c6.checkbox("HbA1c > 9.0%?")

            # 3. Medications (The "Big 5")
            st.markdown("#### 3. Medications")
            c7, c8, c9, c10 = st.columns(4)
            anticoag = c7.checkbox("Anticoagulant")
            antiplatelet = c8.checkbox("Antiplatelet")
            nsaid = c9.checkbox("NSAID Use") # Critical for Kidney Risk
            active_chemo = c10.checkbox("Active Chemo")
            
            c11, c12, c13 = st.columns(3)
            diuretic = c11.checkbox("Diuretic")
            acei = c12.checkbox("ACEi/ARB")
            insulin = c13.checkbox("Insulin")

            # 4. History (New Conditions)
            st.markdown("#### 4. Medical History")
            h1, h2, h3, h4 = st.columns(4)
            gi_bleed = h1.checkbox("Hx GI Bleed") # Critical for Bleeding Model
            liver_disease = h2.checkbox("Liver Disease")
            heart_failure = h3.checkbox("Heart Failure") 
            recent_dka = h4.checkbox("Recent DKA")
            high_bp = st.checkbox("Uncontrolled Hypertension")

            submitted = st.form_submit_button("Run Analysis & Update Dashboard", type="primary")

            if submitted:
                # 1. AI Prediction (Bleeding Model)
                # We map the form inputs to the columns the AI expects
                input_df = pd.DataFrame({
                    'age': [age], 
                    'inr': [inr], 
                    'anticoagulant': [1 if anticoag else 0],
                    'gi_bleed': [1 if gi_bleed else 0], 
                    'high_bp': [1 if high_bp else 0],
                    'antiplatelet': [1 if antiplatelet else 0], 
                    'gender_female': [1 if gender == "Female" else 0],
                    'weight': [weight], 
                    'liver_disease': [1 if liver_disease else 0]
                })
                pred_bleeding = bleeding_model.predict(input_df)[0]
                
                # 2. Rule-Based Prediction (AKI Risk)
                pred_aki = calculate_aki_risk(age, diuretic, acei, high_bp, active_chemo, creat, nsaid, heart_failure)
                
                # 3. Rule-Based Prediction (Hypoglycemia Risk)
                is_renal_impaired = (creat > 1.3)
                pred_hypo = calculate_hypoglycemic_risk(insulin, is_renal_impaired, hba1c_high, False, recent_dka)

                # 4. Update Session State (Connects to Live Dashboard)
                st.session_state['patient_data'] = {
                    'id': 'Calculated Patient', 
                    'age': age,
                    'bleeding_risk': float(pred_bleeding), 
                    'aki_risk': int(pred_aki),
                    'hypo_risk': int(pred_hypo),
                    'status': 'Critical' if (pred_bleeding > 50 or pred_aki > 50) else 'Stable'
                }
                
                st.success("Analysis Complete! Live Dashboard Updated.")
                
                # Quick Result Preview
                r1, r2, r3 = st.columns(3)
                r1.metric("Bleeding Risk (AI)", f"{pred_bleeding:.1f}%")
                r2.metric("AKI Risk (Rule)", f"{pred_aki}%")
                r3.metric("Hypo Risk (Rule)", f"{pred_hypo}%")

    # --- MODULE 3: BATCH ANALYSIS (CSV/IMAGE) --- RESTORED
    elif menu == "Batch Analysis (CSV)":
        st.subheader("Bulk Patient Processing")
        st.markdown("Upload demographics CSV for cohort analysis or medical images for documentation.")

        tab1, tab2 = st.tabs(["📄 CSV Data", "🖼️ Medical Imaging"])

        with tab1:
            uploaded_csv = st.file_uploader("Upload Patient Cohort (CSV)", type=["csv"])
            if uploaded_csv:
                df = pd.read_csv(uploaded_csv)
                st.success(f"Loaded {len(df)} patient records.")
                st.dataframe(df.head())
                st.info("Batch processing pipeline is ready for execution.")

        with tab2:
            uploaded_image = st.file_uploader("Upload Wound/X-Ray (JPG/PNG)", type=["jpg", "png"])
            if uploaded_image:
                st.image(uploaded_image, caption="Uploaded Clinical Image", use_container_width=True)
                st.success("Image tagged and stored in patient record.")

    # --- MODULE 4: MEDICATION CHECKER ---
    elif menu == "Medication Checker":
        st.subheader("Drug-Drug Interaction Checker")
        st.info("Test: **Sildenafil** + **Nitroglycerin**")
        col_d1, col_d2 = st.columns(2)
        d1 = col_d1.text_input("Drug A")
        d2 = col_d2.text_input("Drug B")

        if d1 and d2:
            res = check_interaction(d1, d2)
            if "CRITICAL" in res: st.error(res)
            elif "MAJOR" in res: st.warning(res)
            else: st.success(res)

    # --- MODULE 5: CHATBOT ---
    elif menu == "Clinical Chatbot":
        st.subheader("AI Clinical Assistant")
        q = st.text_input("Ask a clinical question:")
        if q:
            with st.chat_message("assistant"):
                st.write(chatbot_response(q))
