# -*- coding: utf-8 -*-
"""train_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lgDqGUkYjjSXMelXU7E8iHmtTQQy1j09
"""

import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.metrics import mean_squared_error

def train_and_save():
    print("⏳ Generating synthetic clinical data...")
    np.random.seed(42)
    n_samples = 2000 # Increased sample size for better training

    data = pd.DataFrame({
        'age': np.random.randint(18, 95, n_samples),
        'inr': np.random.uniform(0.8, 6.0, n_samples),
        'anticoagulant': np.random.randint(0, 2, n_samples),
        'gi_bleed': np.random.randint(0, 2, n_samples),
        'high_bp': np.random.randint(0, 2, n_samples),
        'antiplatelet': np.random.randint(0, 2, n_samples),
        'gender_female': np.random.randint(0, 2, n_samples),
        'weight': np.random.normal(75, 15, n_samples),
        'liver_disease': np.random.randint(0, 2, n_samples),
    })

    # Ground Truth Logic (The "Teacher")
    def rules(row):
        score = 0
        score += 35 if row['anticoagulant'] else 0
        score += 40 if row['inr'] > 3.5 else 0
        score += 30 if row['gi_bleed'] else 0
        score += 15 if row['antiplatelet'] else 0
        score += 10 if row['age'] > 75 else 0
        return min(score, 100)

    data['risk_score'] = data.apply(rules, axis=1)

    # Train
    print("🧠 Training XGBoost model...")
    X = data.drop('risk_score', axis=1)
    y = data['risk_score']

    model = xgb.XGBRegressor(objective='reg:squarederror', n_estimators=100)
    model.fit(X, y)

    # Test Accuracy
    preds = model.predict(X)
    rmse = np.sqrt(mean_squared_error(y, preds))
    print(f"✅ Model Accuracy Check: RMSE = {rmse:.2f} (Lower is better)")

    # Save
    model.save_model("bleeding_risk_model.json")
    print("💾 Model saved as 'bleeding_risk_model.json'")

if __name__ == "__main__":
    train_and_save()